
//quiz 

// import React, { useState } from "react";
// import { motion } from "framer-motion";
// import { Button } from "@/components/ui/button";
// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
// import { Upload, MessageSquare, Volume2, BookmarkPlus, HelpCircle } from "lucide-react";
// import { useToast } from "@/hooks/use-toast";
// import {
//   Dialog,
//   DialogContent,
//   DialogHeader,
//   DialogTitle,
// } from "@/components/ui/dialog";

// const LearningHub = () => {
//   const { toast } = useToast();
//   const [dragActive, setDragActive] = useState(false);
//   const [uploadedFile, setUploadedFile] = useState<File | null>(null);
//   const [showFeatures, setShowFeatures] = useState(false);
//   const [question, setQuestion] = useState("");
//   const [chatMessages, setChatMessages] = useState<{type: 'user' | 'ai', content: string}[]>([]);
//   const [isGeneratingCards, setIsGeneratingCards] = useState(false);
//   const [flashcards, setFlashcards] = useState<{question: string, answer: string}[]>([]);
//   const [currentCard, setCurrentCard] = useState(0);
//   const [isFlipped, setIsFlipped] = useState(false);

//   // Quiz state
//   const [quizQuestions, setQuizQuestions] = useState<{question: string, options: string[], correctAnswer: number}[]>([]);
//   const [currentQuestion, setCurrentQuestion] = useState(0);
//   const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
//   const [isGeneratingQuiz, setIsGeneratingQuiz] = useState(false);
//   const [quizScore, setQuizScore] = useState<{correct: number, total: number}>({ correct: 0, total: 0 });
//   const [quizSubmitted, setQuizSubmitted] = useState(false);

//   // Handle file upload
//   const handleFileUpload = (file: File) => {
//     setUploadedFile(file);
//     toast({
//       title: "File Uploaded",
//       description: `${file.name} has been uploaded successfully.`,
//     });

//     // Show features popup after successful upload
//     setTimeout(() => {
//       setChatMessages([
//         { 
//           type: 'ai', 
//           content: `I've processed "${file.name}". You can now ask questions about this document or try other features!` 
//         }
//       ]);
//       setShowFeatures(true);
//     }, 1500);
//   };

//   // Handle drag events
//   const handleDrag = (e: React.DragEvent) => {
//     e.preventDefault();
//     e.stopPropagation();
//     if (e.type === "dragenter" || e.type === "dragover") {
//       setDragActive(true);
//     } else if (e.type === "dragleave") {
//       setDragActive(false);
//     }
//   };

//   // Handle drop event
//   const handleDrop = (e: React.DragEvent) => {
//     e.preventDefault();
//     e.stopPropagation();
//     setDragActive(false);

//     if (e.dataTransfer.files && e.dataTransfer.files[0]) {
//       handleFileUpload(e.dataTransfer.files[0]);
//     }
//   };

//   // Handle file input change
//   const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
//     e.preventDefault();
//     if (e.target.files && e.target.files[0]) {
//       handleFileUpload(e.target.files[0]);
//     }
//   };

//   // Handle chat submission
//   const handleChatSubmit = (e: React.FormEvent) => {
//     e.preventDefault();
//     if (!question.trim()) return;

//     // Add user message
//     setChatMessages(prev => [...prev, { type: 'user', content: question }]);

//     // Simulate AI response
//     setTimeout(() => {
//       setChatMessages(prev => [
//         ...prev, 
//         { 
//           type: 'ai', 
//           content: `This is a simulated response to "${question}". In a real application, this would be generated by an AI based on your uploaded document.` 
//         }
//       ]);

//       setQuestion("");
//     }, 1000);
//   };

//   // Handle flashcard generation
//   const handleGenerateFlashcards = () => {
//     if (!uploadedFile) {
//       toast({
//         title: "No Document Uploaded",
//         description: "Please upload a document first to generate flashcards.",
//         variant: "destructive"
//       });
//       return;
//     }

//     setIsGeneratingCards(true);

//     // Simulate flashcard generation
//     setTimeout(() => {
//       setFlashcards([
//         { question: "What is the main purpose of Notedly?", answer: "To help students study smarter through AI-powered tools." },
//         { question: "What file formats can be uploaded to Notedly?", answer: "PDF, Word, and plain text formats." },
//         { question: "How does the Smart Search feature work?", answer: "It uses semantic search to understand context and meaning, not just keywords." },
//       ]);

//       setIsGeneratingCards(false);
//     }, 2000);
//   };

//   // Handle card flip
//   const handleCardFlip = () => {
//     setIsFlipped(!isFlipped);
//   };

//   // Handle next card
//   const handleNextCard = () => {
//     setIsFlipped(false);
//     setCurrentCard(prev => (prev + 1) % flashcards.length);
//   };

//   // Handle previous card
//   const handlePrevCard = () => {
//     setIsFlipped(false);
//     setCurrentCard(prev => (prev - 1 + flashcards.length) % flashcards.length);
//   };

//   // Handle quiz generation
//   const handleGenerateQuiz = () => {
//     if (!uploadedFile) {
//       toast({
//         title: "No Document Uploaded",
//         description: "Please upload a document first to generate a quiz.",
//         variant: "destructive"
//       });
//       return;
//     }

//     setIsGeneratingQuiz(true);
//     setQuizSubmitted(false);
//     setQuizScore({ correct: 0, total: 0 });
//     setSelectedAnswer(null);

//     // Simulate quiz generation
//     setTimeout(() => {
//       setQuizQuestions([
//         { 
//           question: "What is the primary benefit of using AI-powered study tools?", 
//           options: [
//             "They are completely free", 
//             "They personalize learning based on your needs", 
//             "They replace human teachers", 
//             "They only work for certain subjects"
//           ], 
//           correctAnswer: 1 
//         },
//         { 
//           question: "Which feature helps users understand complex topics more easily?", 
//           options: [
//             "File encryption", 
//             "Explain like I'm 5", 
//             "Password protection", 
//             "Font customization"
//           ], 
//           correctAnswer: 1 
//         },
//         { 
//           question: "What makes semantic search different from traditional search?", 
//           options: [
//             "It's faster", 
//             "It's more expensive", 
//             "It understands meaning and context", 
//             "It uses less processing power"
//           ], 
//           correctAnswer: 2 
//         },
//       ]);

//       setCurrentQuestion(0);
//       setIsGeneratingQuiz(false);
//     }, 2000);
//   };

//   // Handle quiz answer selection
//   const handleSelectAnswer = (index: number) => {
//     if (quizSubmitted) return;
//     setSelectedAnswer(index);
//   };

//   // Handle next question in quiz
//   const handleNextQuestion = () => {
//     if (selectedAnswer !== null) {
//       // Update score if answer was correct
//       if (selectedAnswer === quizQuestions[currentQuestion].correctAnswer) {
//         setQuizScore(prev => ({ ...prev, correct: prev.correct + 1 }));
//       }

//       setQuizScore(prev => ({ ...prev, total: prev.total + 1 }));

//       // Move to next question or finish quiz
//       if (currentQuestion < quizQuestions.length - 1) {
//         setCurrentQuestion(prev => prev + 1);
//         setSelectedAnswer(null);
//       } else {
//         setQuizSubmitted(true);
//       }
//     } else {
//       toast({
//         title: "Select an Answer",
//         description: "Please select an answer before continuing.",
//       });
//     }
//   };

//   // Reset quiz
//   const handleResetQuiz = () => {
//     setQuizSubmitted(false);
//     setCurrentQuestion(0);
//     setSelectedAnswer(null);
//     setQuizScore({ correct: 0, total: 0 });
//   };

//   // Handle dialog close
//   const handleDialogClose = () => {
//     setShowFeatures(false);
//   };

//   // Re-open dialog when needed
//   const handleOpenFeatures = () => {
//     if (uploadedFile) {
//       setShowFeatures(true);
//     } else {
//       toast({
//         title: "No Document Uploaded",
//         description: "Please upload a document first to access features.",
//         variant: "destructive"
//       });
//     }
//   };

//   return (
//     <div className="min-h-screen py-10">
//       <div className="container mx-auto px-4">
//         <motion.div
//           initial={{ opacity: 0, y: 20 }}
//           animate={{ opacity: 1, y: 0 }}
//           transition={{ duration: 0.5 }}
//           className="mx-auto"
//         >
//           <h1 className="text-3xl md:text-4xl font-bold text-center mb-8 bg-gradient-to-br from-purple-600 to-blue-500 bg-clip-text text-transparent dark:from-white dark:to-purple-300">
//             Learning Hub
//           </h1>

//           {/* Upload Notes Section */}
//           <Card className="border border-gray-200 dark:border-gray-700 shadow-lg max-w-xl mx-auto">
//             <CardHeader>
//               <CardTitle className="flex items-center gap-2">
//                 <Upload className="h-5 w-5" /> Upload Document
//               </CardTitle>
//             </CardHeader>
//             <CardContent>
//               <div 
//                 className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors ${
//                   dragActive ? 'border-purple-600 bg-purple-600/5' : 'border-gray-300 dark:border-gray-700'
//                 }`}
//                 onDragEnter={handleDrag}
//                 onDragLeave={handleDrag}
//                 onDragOver={handleDrag}
//                 onDrop={handleDrop}
//               >
//                 <Upload className="h-10 w-10 mx-auto mb-4 text-gray-400" />
//                 <h3 className="text-lg font-medium mb-2">
//                   {uploadedFile ? uploadedFile.name : "Drag and drop your document here"}
//                 </h3>

//                 <p className="text-gray-500 dark:text-gray-400 mb-4">
//                   {uploadedFile 
//                     ? `File size: ${(uploadedFile.size / 1024 / 1024).toFixed(2)} MB` 
//                     : "Supported formats: PDF, DOCX, TXT"
//                   }
//                 </p>

//                 {!uploadedFile && (
//                   <div className="mt-4">
//                     <label htmlFor="file-upload" className="cursor-pointer">
//                       <span className="bg-purple-600 hover:bg-purple-500 text-white px-4 py-2 rounded-lg transition-colors">
//                         Browse Files
//                       </span>
//                       <input
//                         id="file-upload"
//                         type="file"
//                         className="hidden"
//                         accept=".pdf,.docx,.doc,.txt"
//                         onChange={handleChange}
//                       />
//                     </label>
//                   </div>
//                 )}

//                 {uploadedFile && (
//                   <div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-4">
//                     <Button
//                       variant="default"
//                       onClick={handleOpenFeatures}
//                     >
//                       Access Features
//                     </Button>
//                     <Button
//                       variant="outline"
//                       onClick={() => setUploadedFile(null)}
//                     >
//                       Remove File
//                     </Button>
//                   </div>
//                 )}
//               </div>
//             </CardContent>
//           </Card>

//           {/* Features Dialog */}
//           <Dialog open={showFeatures} onOpenChange={setShowFeatures}>
//             <DialogContent className="max-w-6xl w-[95vw] max-h-[90vh] overflow-y-auto">
//               <DialogHeader>
//                 <DialogTitle className="flex items-center justify-between">
//                   <span>Document Features</span>
//                   <span className="text-sm font-normal text-gray-500">
//                     {uploadedFile?.name}
//                   </span>
//                 </DialogTitle>
//               </DialogHeader>

//               <div className="grid grid-cols-1 md:grid-cols-12 gap-6 p-4">
//                 {/* Chat Section - Now larger (7/12 columns) */}
//                 <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-7">
//                   <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
//                     <MessageSquare className="h-5 w-5" /> Chat
//                   </h3>

//                   <div className="h-80 mb-4 overflow-y-auto border border-gray-200 dark:border-gray-700 rounded-lg p-4 bg-gray-50 dark:bg-gray-800">
//                     {chatMessages.length === 0 ? (
//                       <div className="h-full flex items-center justify-center text-gray-500 dark:text-gray-400">
//                         Start asking questions about your document.
//                       </div>
//                     ) : (
//                       <div className="space-y-4">
//                         {chatMessages.map((msg, idx) => (
//                           <div 
//                             key={idx}
//                             className={`p-3 rounded-lg max-w-[80%] ${
//                               msg.type === 'user' 
//                                 ? 'bg-purple-600 text-white ml-auto' 
//                                 : 'bg-gray-200 dark:bg-gray-700 mr-auto'
//                             }`}
//                           >
//                             {msg.content}
//                           </div>
//                         ))}
//                       </div>
//                     )}
//                   </div>

//                   <form onSubmit={handleChatSubmit} className="flex gap-2">
//                     <input
//                       type="text"
//                       value={question}
//                       onChange={(e) => setQuestion(e.target.value)}
//                       placeholder="Ask a question about your document..."
//                       className="flex-1 p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800"
//                     />
//                     <Button type="submit">Send</Button>
//                   </form>

//                   <div className="mt-4 flex flex-wrap gap-2">
//                     <Button 
//                       variant="outline" 
//                       size="sm"
//                       onClick={() => {
//                         setQuestion("Summarize this document");
//                         setTimeout(() => handleChatSubmit(new Event('submit') as any), 100);
//                       }}
//                     >
//                       Summarize
//                     </Button>
//                     <Button 
//                       variant="outline" 
//                       size="sm"
//                       onClick={() => {
//                         setQuestion("Explain the key concepts");
//                         setTimeout(() => handleChatSubmit(new Event('submit') as any), 100);
//                       }}
//                     >
//                       Key Concepts
//                     </Button>
//                     <Button 
//                       variant="outline" 
//                       size="sm"
//                       onClick={() => {
//                         setQuestion("Explain like I'm 5");
//                         setTimeout(() => handleChatSubmit(new Event('submit') as any), 100);
//                       }}
//                     >
//                       ELI5
//                     </Button>
//                   </div>
//                 </div>

//                 {/* Audio Section - Now smaller (5/12 columns) */}
//                 <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-5">
//                   <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
//                     <Volume2 className="h-5 w-5" /> Audio
//                   </h3>

//                   <div className="text-center py-6">
//                     <Volume2 className="h-10 w-10 mx-auto mb-4 text-gray-400" />
//                     <p className="text-gray-500 dark:text-gray-400 mb-6">
//                       Convert your notes or AI responses to audio format.
//                     </p>

//                     <div className="max-w-md mx-auto p-4 border border-gray-200 dark:border-gray-700 rounded-lg">
//                       <div className="flex justify-around mb-6">
//                         <Button variant="outline" disabled>Play</Button>
//                         <Button variant="outline" disabled>Pause</Button>
//                         <Button variant="outline" disabled>Stop</Button>
//                       </div>

//                       <div className="flex items-center gap-2 justify-center">
//                         <span className="text-sm">Speed:</span>
//                         <select 
//                           className="border border-gray-300 dark:border-gray-600 rounded p-1 bg-white dark:bg-gray-800"
//                         >
//                           <option value="0.75">0.75x</option>
//                           <option value="1">1x</option>
//                           <option value="1.25">1.25x</option>
//                           <option value="1.5">1.5x</option>
//                           <option value="2">2x</option>
//                         </select>
//                       </div>
//                     </div>

//                     <p className="mt-4 text-sm text-purple-600 dark:text-purple-400">
//                       This feature will be available soon!
//                     </p>
//                   </div>
//                 </div>

//                 {/* Flashcards Section - Increased height */}
//                 <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-6">
//                   <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
//                     <BookmarkPlus className="h-5 w-5" /> Flashcards
//                   </h3>

//                   {!flashcards.length ? (
//                     <div className="text-center py-6 h-64 flex flex-col justify-center">
//                       <BookmarkPlus className="h-10 w-10 mx-auto mb-4 text-gray-400" />
//                       <h3 className="text-lg font-medium mb-2">Flashcard Generator</h3>
//                       <p className="text-gray-500 dark:text-gray-400 mb-4">
//                         Generate flashcards from your uploaded document to help you study.
//                       </p>

//                       <Button 
//                         onClick={handleGenerateFlashcards} 
//                         disabled={isGeneratingCards}
//                         className="mx-auto"
//                       >
//                         {isGeneratingCards ? "Generating..." : "Generate Flashcards"}
//                       </Button>
//                     </div>
//                   ) : (
//                     <div className="h-64 flex flex-col">
//                       <div className="h-48 relative perspective-1000 mb-4">
//                         <motion.div
//                           className="absolute inset-0 bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 p-4 flex items-center justify-center text-center cursor-pointer"
//                           animate={{ rotateY: isFlipped ? 180 : 0 }}
//                           transition={{ duration: 0.6 }}
//                           onClick={handleCardFlip}
//                           style={{ backfaceVisibility: "hidden" }}
//                         >
//                           <div className="text-lg font-medium">
//                             {flashcards[currentCard].question}
//                           </div>
//                         </motion.div>

//                         <motion.div
//                           className="absolute inset-0 bg-purple-600/10 dark:bg-purple-600/20 rounded-xl shadow-lg border border-purple-300 p-4 flex items-center justify-center text-center cursor-pointer"
//                           initial={{ rotateY: -180 }}
//                           animate={{ rotateY: isFlipped ? 0 : -180 }}
//                           transition={{ duration: 0.6 }}
//                           onClick={handleCardFlip}
//                           style={{ backfaceVisibility: "hidden" }}
//                         >
//                           <div className="text-lg">
//                             {flashcards[currentCard].answer}
//                           </div>
//                         </motion.div>
//                       </div>

//                       <div className="flex justify-between mt-auto">
//                         <Button size="sm" variant="outline" onClick={handlePrevCard}>
//                           Previous
//                         </Button>

//                         <div className="text-center">
//                           <span className="text-sm font-medium">
//                             {currentCard + 1} / {flashcards.length}
//                           </span>
//                         </div>

//                         <Button size="sm" variant="outline" onClick={handleNextCard}>
//                           Next
//                         </Button>
//                       </div>

//                       <div className="mt-4 text-center">
//                         <Button 
//                           variant="outline" 
//                           size="sm"
//                           onClick={() => setFlashcards([])}
//                           className="text-red-500 border-red-300"
//                         >
//                           Reset Flashcards
//                         </Button>
//                       </div>
//                     </div>
//                   )}
//                 </div>

//                 {/* Quiz Section - New section */}
//                 <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-6">
//                   <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
//                     <HelpCircle className="h-5 w-5" /> Quiz
//                   </h3>

//                   {!quizQuestions.length ? (
//                     <div className="text-center py-6 h-64 flex flex-col justify-center">
//                       <HelpCircle className="h-10 w-10 mx-auto mb-4 text-gray-400" />
//                       <h3 className="text-lg font-medium mb-2">Quiz Generator</h3>
//                       <p className="text-gray-500 dark:text-gray-400 mb-4">
//                         Test your knowledge with a quiz based on your document.
//                       </p>

//                       <Button 
//                         onClick={handleGenerateQuiz} 
//                         disabled={isGeneratingQuiz}
//                         className="mx-auto"
//                       >
//                         {isGeneratingQuiz ? "Generating..." : "Generate Quiz"}
//                       </Button>
//                     </div>
//                   ) : (
//                     <div className="h-64 flex flex-col">
//                       {quizSubmitted ? (
//                         <div className="text-center flex flex-col items-center justify-center h-full">
//                           <h3 className="text-xl font-medium mb-4">Quiz Results</h3>
//                           <div className="text-3xl font-bold mb-6">
//                             {quizScore.correct} / {quizScore.total}
//                           </div>
//                           <p className="text-gray-500 dark:text-gray-400 mb-6">
//                             {quizScore.correct === quizScore.total 
//                               ? "Perfect! You've mastered this material."
//                               : quizScore.correct > quizScore.total / 2
//                                 ? "Good job! Keep studying to improve further."
//                                 : "Keep studying to improve your score!"
//                             }
//                           </p>
//                           <Button onClick={handleResetQuiz}>Try Again</Button>
//                         </div>
//                       ) : (
//                         <>
//                           <div className="mb-4">
//                             <h4 className="text-lg font-medium mb-3">
//                               Question {currentQuestion + 1} of {quizQuestions.length}
//                             </h4>
//                             <p className="mb-4">{quizQuestions[currentQuestion].question}</p>

//                             <div className="space-y-2">
//                               {quizQuestions[currentQuestion].options.map((option, idx) => (
//                                 <div 
//                                   key={idx}
//                                   className={`p-3 border rounded-lg cursor-pointer transition-colors ${
//                                     selectedAnswer === idx 
//                                       ? 'bg-purple-100 border-purple-500 dark:bg-purple-900/30 dark:border-purple-500' 
//                                       : 'hover:bg-gray-50 dark:hover:bg-gray-800'
//                                   }`}
//                                   onClick={() => handleSelectAnswer(idx)}
//                                 >
//                                   {option}
//                                 </div>
//                               ))}
//                             </div>
//                           </div>

//                           <div className="mt-auto flex justify-end">
//                             <Button onClick={handleNextQuestion}>
//                               {currentQuestion < quizQuestions.length - 1 ? "Next Question" : "Submit Quiz"}
//                             </Button>
//                           </div>
//                         </>
//                       )}
//                     </div>
//                   )}
//                 </div>
//               </div>
//             </DialogContent>
//           </Dialog>
//         </motion.div>
//       </div>
//     </div>
//   );
// };

// export default LearningHub;


import React, { useState, useEffect, useRef } from "react"; // Added useEffect
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Upload, MessageSquare, Volume2, BookmarkPlus, HelpCircle, Loader2, AlertCircle, StopCircle, Pause, Play, Ear } from "lucide-react"; // Added Loader2, AlertCircle
import { useToast } from "@/hooks/use-toast"; // Assuming this is Shadcn's useToast
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter, // Maybe useful for close button
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input"; // Use Shadcn Input
import { Textarea } from "@/components/ui/textarea"; // Use Shadcn Textarea for consistency
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; // Assuming Shadcn Select

// Define types for API responses (optional but good practice)
interface Flashcard {
  question: string;
  answer: string;
}

interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswer: number; // Index
}

const LearningHub = () => {
  const { toast } = useToast();
  const [dragActive, setDragActive] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<{ name: string; size: number } | null>(null); // Store only metadata
  const [documentId, setDocumentId] = useState<string | null>(null); // NEW: Store the ID from backend
  const [isUploading, setIsUploading] = useState(false); // NEW: Loading state for upload
  const [uploadError, setUploadError] = useState<string | null>(null); // NEW: Error state for upload

  const [showFeatures, setShowFeatures] = useState(false);

  // Chat State
  const [question, setQuestion] = useState("");
  const [chatMessages, setChatMessages] = useState<{ type: 'user' | 'ai'; content: string }[]>([]);
  const [isChatLoading, setIsChatLoading] = useState(false); // NEW: Loading state for chat

  // Flashcard State
  const [flashcards, setFlashcards] = useState<Flashcard[] | null>(null);
  const [isGeneratingFlashcards, setIsGeneratingFlashcards] = useState<boolean>(false);
  const [flashcardError, setFlashcardError] = useState<string | null>(null);
  // Assume you have the documentId stored in a state variable, e.g., currentDocumentId
  const [currentDocumentId, setCurrentDocumentId] = useState<string | null>(/* initial value, perhaps from upload response */);


  // Quiz State
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [isGeneratingQuiz, setIsGeneratingQuiz] = useState(false);
  const [quizScore, setQuizScore] = useState<{ correct: number; total: number }>({ correct: 0, total: 0 });
  const [quizSubmitted, setQuizSubmitted] = useState(false);

// --- NEW Audio State ---
// const AudioSection = () => {
  // --- State Variables ---
  const [isGeneratingAudio, setIsGeneratingAudio] = useState(false);
  const [audioSrc, setAudioSrc] = useState<string | null>(null); // Will hold the Object URL
  const [playbackSpeed, setPlaybackSpeed] = useState(1);
  const [isPlaying, setIsPlaying] = useState(false);
  const [tutorExplanationText, setTutorExplanationText] = useState<string>(''); // State to hold the fetched text
  const [error, setError] = useState<string | null>(null); // State for displaying errors

  // --- Refs ---
  const audioRef = useRef<HTMLAudioElement>(null);
// --- End Audio State ---

  // --- Helper function for API calls ---
  const makeApiCall = async (endpoint: string, options: RequestInit = {}) => {
    try {
      const response = await fetch(`/api${endpoint}`, { // Use relative path for proxy
        ...options,
        headers: {
          'Content-Type': 'application/json',
          ...options.headers,
        },
      });

      const data = await response.json(); // Try to parse JSON regardless of status

      if (!response.ok) {
        console.error("API Error Response:", data);
        throw new Error(data.error || `HTTP error ${response.status}`);
      }
      return data;
    } catch (error: any) {
      console.error(`API call to ${endpoint} failed:`, error);
      toast({
        title: "API Error",
        description: error.message || "An unknown error occurred",
        variant: "destructive",
      });
      throw error; // Re-throw to be caught by calling function if needed
    }
  };
const FLASK_BACKEND_URL = 'http://127.0.0.1:5555'

  useEffect(() => {
    const fetchExplanation = async () => {
        setError(null); // Clear previous errors
        console.log("Attempting to fetch explanation text...");
        try {
            const response = await fetch(`${FLASK_BACKEND_URL}/api/getTutorExplanation`);
            console.log("Fetch response status:", response.status);

            if (!response.ok) {
                // Try to get error message from response if available
                let errorMsg = `HTTP error! Status: ${response.status}`;
                try {
                    const errData = await response.json(); // Try parsing JSON error
                    errorMsg = errData.error || errorMsg;
                } catch (_) {
                    // If not JSON, try getting text error
                    try {
                       const errText = await response.text();
                       errorMsg = errText || errorMsg;
                    } catch { /* Ignore if response is not text either */ }
                }
                throw new Error(errorMsg);
            }

            const data = await response.text(); // Expecting plain text
            console.log("Fetched explanation text (first 100 chars):", data.substring(0, 100));

            if (!data) {
                throw new Error("Received empty explanation text from server.");
            }
            setTutorExplanationText(data);
        } catch (error: any) {
            console.error("Failed to fetch tutor_explanation.txt:", error);
            setError(`Failed to load explanation: ${error.message}`);
            setTutorExplanationText(''); // Ensure text is empty on error
        }
    };

    fetchExplanation();
}, []);

// Empty dependency array means this runs once when the component mounts
// --- End Fetch Effect ---  // // Handle file upload - UPDATED
  // const handleFileUpload = async (file: File) => {
  //   setIsUploading(true);
  //   setUploadError(null);
  //   setDocumentId(null); // Reset previous document
  //   setUploadedFile(null);
  //   // Reset features
  //   setChatMessages([]);
  //   setFlashcards([]);
  //   setQuizQuestions([]);
  //   setShowFeatures(false);


  //   const formData = new FormData();
  //   formData.append("file", file);

  //   try {
  //       // Use fetch to send to backend (Vite proxy handles routing)
  //       const response = await fetch('/api/upload', { // No need for full URL due to proxy
  //           method: 'POST',
  //           body: formData, // FormData sets Content-Type automatically
  //       });

  //       const data = await response.json(); // Try parsing JSON always

  //       if (!response.ok) {
  //           throw new Error(data.error || `Upload failed with status: ${response.status}`);
  //       }

  //       setDocumentId(data.documentId); // Store the returned document ID
  //       setUploadedFile({ name: data.filename || file.name, size: file.size }); // Use filename from response if available

  //       toast({
  //           title: "File Uploaded & Processed",
  //           description: `${data.filename || file.name} is ready. Access features now.`,
  //       });

  //       // Add initial AI message and show features
  //       setChatMessages([{
  //           type: 'ai',
  //           content: `I've processed "${data.filename || file.name}". Ask questions or generate study materials!`
  //       }]);
  //       setShowFeatures(true);

  //   } catch (error: any) {
  //       console.error("Upload failed:", error);
  //       setUploadError(error.message || "An unknown error occurred during upload.");
  //       toast({
  //           title: "Upload Failed",
  //           description: error.message || "Could not upload or process the file.",
  //           variant: "destructive",
  //       });
  //   } finally {
  //       setIsUploading(false);
  //   }
  // };

  const handleFileUpload = async (file: File) => {
    setIsUploading(true);
    setUploadError(null);
    setDocumentId(null); // Reset previous document
    setUploadedFile(null);
    setChatMessages([]);
    setFlashcards([]);
    setQuizQuestions([]);
    setShowFeatures(false);

    const formData = new FormData();
    formData.append("file", file);

    console.log("📤 Uploading file:", file.name);

    try {
      const response = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });

      // Try to parse JSON response no matter the status
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || `Upload failed with status: ${response.status}`);
      }

      console.log("✅ Upload response:", data);

      setDocumentId(data.documentId);
      setUploadedFile({
        name: data.filename || file.name,
        size: file.size,
      });

      toast({
        title: "File Uploaded & Processed",
        description: `${data.filename || file.name} is ready. Access features now.`,
      });

      setChatMessages([
        {
          type: "ai",
          content: `I've processed "${data.filename || file.name}". Ask questions or generate study materials!`,
        },
      ]);

      setShowFeatures(true);

    } catch (error: any) {
      console.error("❌ Upload failed:", error);
      setUploadError(error.message || "An unknown error occurred during upload.");
      toast({
        title: "Upload Failed",
        description: error.message || "Could not upload or process the file.",
        variant: "destructive",
      });
    } finally {
      setIsUploading(false);
    }
  };


  // Handle drag events (no change needed)
  const handleDrag = (e: React.DragEvent) => { /* ... */ };
  const handleDrop = (e: React.DragEvent) => { /* ... */ };
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => { /* ... */ };


  // Handle chat submission - UPDATED
  const handleChatSubmit = async (e?: React.FormEvent) => {
    e?.preventDefault(); // Allow calling without event (e.g., from buttons)
    if (!question.trim() || !documentId || isChatLoading) return;

    const userMessage = question;
    setChatMessages(prev => [...prev, { type: 'user', content: userMessage }]);
    setQuestion(""); // Clear input immediately
    setIsChatLoading(true);

    try {
      const data = await makeApiCall('/chat', {
        method: 'POST',
        body: JSON.stringify({ documentId, question: userMessage }),
      });

      setChatMessages(prev => [...prev, { type: 'ai', content: data.response }]);

    } catch (error) {
      // Error toast is handled by makeApiCall
      // Optionally add a specific error message in chat
      setChatMessages(prev => [...prev, { type: 'ai', content: "Sorry, I couldn't get a response. Please try again." }]);
    } finally {
      setIsChatLoading(false);
    }
  };

// --- Handler Function: Generate Audio by calling Flask /tts endpoint ---
const handleGenerateAudio = async () => {
  if (!tutorExplanationText) {
      setError("Cannot generate audio: Tutor explanation text is not loaded.");
      return;
  }

  setIsGeneratingAudio(true);
  setAudioSrc(null); // Clear previous audio source immediately
  setError(null); // Clear previous errors

  // --- Important: Revoke previous object URL if it exists BEFORE fetching new one ---
  if (audioSrc && audioSrc.startsWith('blob:')) {
      URL.revokeObjectURL(audioSrc);
      // console.log("Revoked previous Object URL:", audioSrc); // For debugging
  }
  // ---

  console.log("Requesting TTS generation from backend...");
  try {
      // Make POST request to the Flask /tts endpoint
      const response = await fetch(`${FLASK_BACKEND_URL}/tts`, {
          method: 'POST',
          // No body is needed since the Flask endpoint reads the file itself
          // headers: { 'Content-Type': 'application/json', }, // Not needed if no body
      });

      console.log("TTS response status:", response.status);

      if (!response.ok) {
          // Try to get error message from response
           let errorMsg = `TTS generation failed: ${response.status}`;
           try {
               const errData = await response.json();
               errorMsg = errData.error || errorMsg;
           } catch (_) {
              try {
                 const errText = await response.text();
                 errorMsg = errText || errorMsg;
              } catch { /* Ignore if response is not text either */ }
           }
           throw new Error(errorMsg);
      }

      // Handle the raw audio data (Blob)
      const audioBlob = await response.blob();
      console.log("Received audio blob, size:", audioBlob.size, "type:", audioBlob.type);

      if (audioBlob.size === 0) {
          throw new Error("Received empty audio data from server.");
      }
      if (audioBlob.type !== 'audio/mpeg') {
          console.warn("Received blob type is not 'audio/mpeg', it is:", audioBlob.type, ". Playback might fail.");
      }

      // Create an Object URL from the Blob
      const objectUrl = URL.createObjectURL(audioBlob);
      console.log("Created Object URL:", objectUrl);
      setAudioSrc(objectUrl); // Set the new audio source

  } catch (error: any) {
      console.error("Error generating or processing audio:", error);
      setError(`Audio generation failed: ${error.message}`);
      setAudioSrc(null); // Ensure no audio source on error
  } finally {
      setIsGeneratingAudio(false);
  }
};
// --- End Generate Audio Handler ---


// --- Audio Player Control Handlers ---
const togglePlayPause = () => {
  const audioElement = audioRef.current;
  if (!audioElement || !audioSrc) return; // Don't do anything if no element or source

  if (isPlaying) {
      audioElement.pause();
  } else {
      audioElement.play().catch(e => {
          console.error("Error playing audio:", e);
          setError("Could not play audio. Interaction might be required.");
          setIsPlaying(false); // Ensure state is correct if play fails
      });
  }
  setIsPlaying(!isPlaying);
};


const handleStop = () => {
  const audioElement = audioRef.current;
  if (!audioElement) return;

  audioElement.pause();
  audioElement.currentTime = 0; // Reset playback position
  setIsPlaying(false);
};



const handleSpeedChange = (speed: string) => {
  const newSpeed = parseFloat(speed);
  setPlaybackSpeed(newSpeed);
  // The effect hook below will handle applying the speed to the audio element
};
// --- End Player Control Handlers ---



 // --- NEW: Effects for Audio Playback ---

//  // Effect to play/pause audio element when isPlaying state changes [10]
//  useEffect(() => {
//      if (audioRef.current) {
//          if (isPlaying) {
//              audioRef.current.play().catch(error => {
//                  console.error("Audio play failed:", error);
//                  setIsPlaying(false); // Reset state if play fails
//                  toast({ title: "Playback Error", description: "Could not play audio.", variant: "destructive" });
//              });
//          } else {
//              audioRef.current.pause();
//          }
//      }
//  }, [isPlaying]);

 // Effect to handle audio ending
//  useEffect(() => {
//      const audioElement = audioRef.current;
//      const handleAudioEnd = () => setIsPlaying(false);

//      if (audioElement) {
//          audioElement.addEventListener('ended', handleAudioEnd);
//          return () => {
//              audioElement.removeEventListener('ended', handleAudioEnd);
//          };
//      }
//  }, []); // Run only once

 // Effect to cleanup Blob URL when component unmounts or src changes [5]
//  useEffect(() => {
//      const currentAudioSrc = audioSrc; // Capture src on effect run
//      return () => {
//          if (currentAudioSrc) {
//              URL.revokeObjectURL(currentAudioSrc);
//              // console.log("Revoked audio URL:", currentAudioSrc);
//          }
//      };
//  }, [audioSrc]);

 // Effect to set initial playback rate when audio source loads
//  useEffect(() => {
//    if (audioRef.current && audioSrc) {
//      audioRef.current.playbackRate = playbackSpeed;
//    }
//  }, [audioSrc]); // Re-apply speed if source changes

 // --- Effect Hook: Update Playback Speed ---
 useEffect(() => {
  if (audioRef.current) {
      audioRef.current.playbackRate = playbackSpeed;
  }
}, [playbackSpeed, audioSrc]); // Update speed if source changes too
// --- End Speed Effect ---

// --- Effect Hook: Cleanup Object URL ---
// This is crucial to prevent memory leaks
useEffect(() => {
  // This function runs when the component unmounts or *before* the effect runs again due to dependency changes
  return () => {
      if (audioSrc && audioSrc.startsWith('blob:')) {
          URL.revokeObjectURL(audioSrc);
          // console.log("Cleaned up Object URL:", audioSrc); // For debugging
      }
  };
}, [audioSrc]); // Dependency array ensures cleanup runs when audioSrc changes
// --- End Cleanup Effect ---



  // Handle flashcard generation - UPDATED
// Inside your LearningHub component

const handleGenerateFlashcards = async () => {
  if (!currentDocumentId) {
    setFlashcardError("No document selected or uploaded.");
    return;
  }

  setIsGeneratingFlashcards(true);
  setFlashcardError(null);
  setFlashcards(null); // Clear previous flashcards

  try {
    // Replace with your actual Flask server URL/port [3]
    const response = await fetch('http://127.0.0.1:5555/api/generate_flashcards', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ documentId: currentDocumentId }),
    });

    if (!response.ok) {
      // Try to get error message from backend response
      const errorData = await response.json().catch(() => ({ error: 'Failed to generate flashcards. Server returned an error.' }));
      throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    // Add basic validation on frontend too
    if (data.flashcards && Array.isArray(data.flashcards)) {
       setFlashcards(data.flashcards);
    } else {
       throw new Error("Received invalid flashcard data format from server.");
    }

  } catch (error: any) {
    console.error("Error generating flashcards:", error);
    setFlashcardError(error.message || "An unknown error occurred while generating flashcards.");
    setFlashcards(null);
  } finally {
    setIsGeneratingFlashcards(false);
  }
};

  // Handle quiz generation - UPDATED
  const handleGenerateQuiz = async () => {
    if (!documentId || isGeneratingQuiz) return;

    setIsGeneratingQuiz(true);
    setQuizQuestions([]); // Clear previous quiz
    setQuizSubmitted(false);
    setQuizScore({ correct: 0, total: 0 });
    setSelectedAnswer(null);
    setCurrentQuestion(0);

    try {
      const data = await makeApiCall('/generate_quiz', {
        method: 'POST',
        body: JSON.stringify({ documentId }),
      });

      if (data.quizQuestions && data.quizQuestions.length > 0) {
        setQuizQuestions(data.quizQuestions);
        toast({
          title: "Quiz Generated",
          description: `Created a ${data.quizQuestions.length}-question quiz.`,
        });
      } else {
        toast({
          title: "No Quiz Questions",
          description: "Could not generate a quiz from this document.",
        });
      }

    } catch (error) {
      // Error handled by makeApiCall
    } finally {
      setIsGeneratingQuiz(false);
    }
  };

  // Quiz interaction logic (handleSelectAnswer, handleNextQuestion, handleResetQuiz) - no change needed
  const handleSelectAnswer = (index: number) => { /* ... */ };
  const handleNextQuestion = () => { /* ... */ };
  const handleResetQuiz = () => { /* ... */ };


  // Dialog management (no change needed)
  const handleDialogClose = () => setShowFeatures(false);
  const handleOpenFeatures = () => { /* ... */ };

  // NEW: Cleanup function to potentially clear document on backend when component unmounts or file changes
  useEffect(() => {
    const currentDocId = documentId; // Capture ID at the time effect runs
    return () => {
      if (currentDocId) {
        // Optional: Tell backend to remove the document when component unmounts
        // or a new file is uploaded. This helps manage the in-memory store.
        // Consider if this is the desired behavior (e.g., user might navigate away and back)
        // fetch(`/api/clear_document/${currentDocId}`, { method: 'DELETE' });
        // console.log(`Requested cleanup for doc: ${currentDocId}`);
      }
    };
  }, [documentId]); // Rerun effect when documentId changes


  // --- RENDER LOGIC ---
  // (Minor adjustments below for loading/error states)

  return (
    <div className="min-h-screen py-10">
      <div className="container mx-auto px-4">
        <motion.div /* ... */ >
          <h1 /* ... */ >Learning Hub</h1>

          {/* Upload Card */}
          <Card className="border border-gray-200 dark:border-gray-700 shadow-lg max-w-xl mx-auto">
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Upload className="h-5 w-5" /> Upload Document
                </div>
                {isUploading && <Loader2 className="h-5 w-5 animate-spin text-purple-600" />}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div /* Drag and Drop Area */
                className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors ${dragActive ? 'border-purple-600 bg-purple-600/5' : 'border-gray-300 dark:border-gray-700'
                  } ${isUploading ? 'opacity-50 cursor-not-allowed' : ''}`}
                onDragEnter={!isUploading ? handleDrag : undefined}
                onDragLeave={!isUploading ? handleDrag : undefined}
                onDragOver={!isUploading ? handleDrag : undefined}
                onDrop={!isUploading ? handleDrop : undefined}
              >
                <Upload className="h-10 w-10 mx-auto mb-4 text-gray-400" />
                <h3 className="text-lg font-medium mb-2">
                  {isUploading ? "Uploading..." : uploadedFile ? uploadedFile.name : "Drag and drop your document here"}
                </h3>
                <p className="text-gray-500 dark:text-gray-400 mb-4">
                  {uploadedFile
                    ? `Size: ${(uploadedFile.size / 1024 / 1024).toFixed(2)} MB`
                    : "Supported: PDF, DOCX, TXT"}
                </p>

                {!uploadedFile && !isUploading && (
                  <div className="mt-4">
                    <label htmlFor="file-upload" className={`cursor-pointer ${isUploading ? 'opacity-50' : ''}`}>
                      <span className="bg-purple-600 hover:bg-purple-500 text-white px-4 py-2 rounded-lg transition-colors">
                        Browse Files
                      </span>
                      {/* <input
                        id="file-upload" type="file" className="hidden"
                        accept=".pdf,.docx,.doc,.txt"
                        onChange={!isUploading ? handleChange : undefined}
                        disabled={isUploading}
                      /> */}
                      <input
                        type="file"
                        accept=".pdf,.docx,.txt"
                        onChange={(e) => {
                          const file = e.target.files?.[0];
                          if (file) handleFileUpload(file);
                        }}
                      />

                    </label>
                  </div>
                )}

                {uploadError && !isUploading && (
                  <div className="mt-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-md text-sm flex items-center gap-2">
                    <AlertCircle className="h-5 w-5" /> {uploadError}
                  </div>
                )}

                {documentId && !isUploading && (
                  <div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-4">
                    <Button onClick={handleOpenFeatures}>Access Features</Button>
                    <Button variant="outline" onClick={() => {
                      setUploadedFile(null);
                      setDocumentId(null);
                      // Optional: Clear backend storage too
                      // if (documentId) fetch(`/api/clear_document/${documentId}`, { method: 'DELETE' });
                    }}>
                      Remove File
                    </Button>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Features Dialog */}
          <Dialog open={showFeatures} onOpenChange={setShowFeatures}>
            <DialogContent className="max-w-6xl w-[95vw] max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle className="flex items-center justify-between">
                  <span>Features for:</span>
                  <span className="text-sm font-normal text-gray-500 truncate max-w-xs sm:max-w-sm md:max-w-md" title={uploadedFile?.name}>
                    {uploadedFile?.name}
                  </span>
                </DialogTitle>
              </DialogHeader>

              <div className="grid grid-cols-1 md:grid-cols-12 gap-6 p-4">
                {/* Chat Section */}
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-7">
                  <h3 className="text-lg font-semibold mb-4 flex items-center justify-between">
                    <div className="flex items-center gap-2"> <MessageSquare className="h-5 w-5" /> Chat </div>
                    {isChatLoading && <Loader2 className="h-5 w-5 animate-spin text-purple-600" />}
                  </h3>
                  <div className="h-80 mb-4 overflow-y-auto border border-gray-200 dark:border-gray-700 rounded-lg p-4 bg-gray-50 dark:bg-gray-800/50 space-y-4">
                    {chatMessages.map((msg, idx) => (<div /* Chat Message Styling */ >{msg.content}</div>))}
                    {isChatLoading && <div className="text-center text-gray-500"><Loader2 className="h-4 w-4 animate-spin inline mr-1" />Thinking...</div>}
                    {chatMessages.length === 0 && !isChatLoading && (
                      <div className="h-full flex items-center justify-center text-gray-500 dark:text-gray-400">Ask questions about your document.</div>
                    )}
                  </div>
                  <form onSubmit={handleChatSubmit} className="flex gap-2">
                    <Input // Use Shadcn Input
                      type="text" value={question}
                      onChange={(e) => setQuestion(e.target.value)}
                      placeholder="Ask a question..."
                      className="flex-1"
                      disabled={isChatLoading || !documentId}
                    />
                    <Button type="submit" disabled={isChatLoading || !documentId || !question.trim()}>Send</Button>
                  </form>
                  <div className="mt-4 flex flex-wrap gap-2">
                    {/* Quick Action Buttons - Disable while loading */}
                    <Button variant="outline" size="sm" disabled={isChatLoading || !documentId} onClick={() => { setQuestion("Summarize this document"); setTimeout(() => handleChatSubmit(), 0); }}>Summarize</Button>
                    <Button variant="outline" size="sm" disabled={isChatLoading || !documentId} onClick={() => { setQuestion("Explain the key concepts"); setTimeout(() => handleChatSubmit(), 0); }}>Key Concepts</Button>
                    <Button variant="outline" size="sm" disabled={isChatLoading || !documentId} onClick={() => { setQuestion("Explain like I'm 5"); setTimeout(() => handleChatSubmit(), 0); }}>ELI5</Button>
                  </div>
                </div>

{/* Audio Section - UPDATED */}
          <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-5 flex flex-col min-h-[300px]"> {/* Added min-height */}
            {/* Header */}
            <h3 className="text-lg font-semibold mb-4 flex items-center justify-between">
                <div className="flex items-center gap-2"><Volume2 className="h-5 w-5" /> Audio Player</div>
                {isGeneratingAudio && <Loader2 className="h-5 w-5 animate-spin text-purple-600" />}
            </h3>

            {/* Main Content Area */}
            <div className="text-center flex-grow flex flex-col justify-center">
                <Ear className="h-10 w-10 mx-auto mb-4 text-gray-400" />

                {/* Status/Error Messages */}
                {error && (
                    <p className="text-red-500 dark:text-red-400 mb-4 text-sm px-4 break-words">
                        Error: {error}
                    </p>
                )}
                <p className="text-gray-500 dark:text-gray-400 mb-4 text-sm">
                    {tutorExplanationText ? "Generate audio from the loaded tutor explanation." : "Loading explanation text..."}
                </p>

                {/* Generate Audio Button */}
                <Button
                    onClick={handleGenerateAudio}
                    // Button is disabled if currently generating OR if the text hasn't loaded yet
                    // disabled={isGeneratingAudio || !tutorExplanationText}
                    className="mb-6 mx-auto"
                    size="sm"
                >
                    {isGeneratingAudio ? 'Generating...' : 'Generate Audio'}
                </Button>

                {/* Hidden Audio Element */}
                <audio
                    ref={audioRef}
                    src={audioSrc || undefined} // Use the object URL or undefined if null
                    onEnded={() => setIsPlaying(false)} // Reset play button when audio finishes naturally
                    onPause={() => setIsPlaying(false)} // Handle pause events (e.g., from stop button)
                    onPlay={() => setIsPlaying(true)}   // Ensure playing state is true when playback starts/resumes
                    onError={(e) => {
                        console.error("Audio Element Error:", e);
                        setError("Error loading or playing audio file.");
                        setAudioSrc(null); // Clear broken source
                        setIsPlaying(false);
                    }}
                    // Consider adding controls={true} temporarily for debugging if needed
                />

                {/* Player Controls Area */}
                <div className={`max-w-sm mx-auto p-4 border border-gray-200 dark:border-gray-700 rounded-lg ${!audioSrc ? 'opacity-50 cursor-not-allowed' : ''}`}>
                    {/* Play/Pause/Stop Buttons */}
                    <div className="flex justify-around mb-4">
                        <Button variant="outline" size="icon" onClick={togglePlayPause} disabled={!audioSrc || isGeneratingAudio}>
                            {isPlaying ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
                        </Button>
                        <Button variant="outline" size="icon" onClick={handleStop} disabled={!audioSrc || isGeneratingAudio}>
                            <StopCircle className="h-4 w-4" />
                        </Button>
                    </div>

                    {/* Speed Selector */}
                    <div className="flex items-center gap-2 justify-center">
                        <span className="text-sm">Speed:</span>
                        <Select
                            value={String(playbackSpeed)}
                            onValueChange={handleSpeedChange} // Correct handler
                            disabled={!audioSrc || isGeneratingAudio}
                        >
                            <SelectTrigger className="w-[80px] h-8 text-xs">
                                <SelectValue placeholder="Speed" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="0.75">0.75x</SelectItem>
                                <SelectItem value="1">1x</SelectItem>
                                <SelectItem value="1.25">1.25x</SelectItem>
                                <SelectItem value="1.5">1.5x</SelectItem>
                                <SelectItem value="2">2x</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                </div>
            </div>
        </div>                {/* --- End Updated Audio Section --- */}

                {/* Flashcards Section */}
                // Inside the JSX return block of your LearningHub component

<div>
  {/* Button to trigger generation (only enable if a document is loaded) */}
  <button
    onClick={handleGenerateFlashcards}
    disabled={!currentDocumentId || isGeneratingFlashcards}
  >
    {isGeneratingFlashcards ? 'Generating...' : 'Generate Flashcards'}
  </button>

  {/* Display Loading State */}
  {isGeneratingFlashcards && <p>Loading flashcards...</p>}

  {/* Display Error State */}
  {flashcardError && <p style={{ color: 'red' }}>Error: {flashcardError}</p>}

  {/* Display Flashcards */}
  {flashcards && flashcards.length > 0 && (
    <div>
      <h3>Generated Flashcards</h3>
      {flashcards.map((card, index) => (
        <div key={index} style={{ border: '1px solid #ccc', margin: '10px', padding: '10px' }}>
          <p><strong>Q:</strong> {card.question}</p>
          {/* You might want to initially hide the answer */}
          <p><strong>A:</strong> {card.answer}</p>
        </div>
      ))}
    </div>
  )}
   {flashcards && flashcards.length === 0 && !isGeneratingFlashcards && !flashcardError && (
     <p>No flashcards were generated for this document.</p>
   )}
</div>

                {/* Quiz Section */}
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:col-span-6 min-h-[300px]"> {/* Added min-height */}
                  <h3 className="text-lg font-semibold mb-4 flex items-center gap-2"><HelpCircle className="h-5 w-5" /> Quiz</h3>
                  {!quizQuestions.length && !isGeneratingQuiz && (
                    <div className="text-center py-6 h-full flex flex-col justify-center items-center">
                      <HelpCircle className="h-10 w-10 mx-auto mb-4 text-gray-400" />
                      <p className="text-gray-500 dark:text-gray-400 mb-4">Test your knowledge with a quiz.</p>
                      <Button onClick={handleGenerateQuiz} disabled={!documentId}>Generate Quiz</Button>
                    </div>
                  )}
                  {isGeneratingQuiz && (
                    <div className="text-center py-6 h-full flex flex-col justify-center items-center text-gray-500">
                      <Loader2 className="h-8 w-8 animate-spin mb-4 text-purple-600" /> Generating quiz...
                    </div>
                  )}
                  {quizQuestions.length > 0 && !isGeneratingQuiz && (
                    <div className="h-full flex flex-col"> {/* Ensure quiz container fills space */}
                      {quizSubmitted ? (
                        <div className="text-center flex flex-col items-center justify-center h-full"> {/* Quiz Results */} </div>
                      ) : (
                        <> {/* Quiz Question Display */} </>
                      )}
                      {/* Reset/Try Again Button */}
                      <div className="mt-auto pt-4 text-center">
                        {quizSubmitted && <Button onClick={handleResetQuiz} variant="outline">Try Again</Button>}
                        {!quizSubmitted && <Button variant="link" size="sm" onClick={() => setQuizQuestions([])} className="text-red-500 hover:text-red-600">Clear Quiz</Button>}
                      </div>
                    </div>
                  )}
                </div>

              </div>
              {/* Optional: Add a close button to the dialog footer */}
              {/* <DialogFooter> <Button variant="outline" onClick={handleDialogClose}>Close</Button> </DialogFooter> */}
            </DialogContent>
          </Dialog>
        </motion.div>
      </div>
    </div>
  );
};

  // Ensure all braces are properly closed

export default LearningHub;
